##### ON RENDER ####
#GET all contacts
GET https://test-f9oo.onrender.com/contacts

###GET contact by id

GET https://test-f9oo.onrender.com/contacts/650cb309628c58406f5751e0

###POST new contact

POST https://test-f9oo.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "any",
  "lastName": "any",
  "email": "any",
  "favoriteColor": "any",
  "birthday": "any"
}

###PUT update Contact info
PUT https://test-f9oo.onrender.com/contacts/650cb309628c58406f5751e0
Content-Type: application/json

{
  "firstName": "any",
  "lastName": "any",
  "email": "any",
  "favoriteColor": "any",
  "birthday": "any"
}

###DELETE contact by id
DELETE https://test-f9oo.onrender.com/contacts/650cb309628c58406f5751e0


###DELETE ALL contacts
DELETE https://test-f9oo.onrender.com/contacts








#### LOCALHOST ####
###GET all contacts
GET http://localhost:3000/contacts

###GET contact by id

GET http://localhost:3000/contacts/650cb309628c58406f5751e0

###POST new contact

POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "any",
  "lastName": "any",
  "email": "any",
  "favoriteColor": "any",
  "birthday": "any"
}

###PUT update Contact info
PUT http://localhost:3000/contacts/650cb309628c58406f5751e0
Content-Type: application/json

{
  "firstName": "any",
  "lastName": "any",
  "email": "any",
  "favoriteColor": "any",
  "birthday": "any"
}

###DELETE contact by id
DELETE http://localhost:3000/contacts/650cb309628c58406f5751e0


###DELETE ALL contacts
DELETE http://localhost:3000/contacts